name: Interacto Angular CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build-prod

      - name: Test
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test-headless

